import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Network",
    projects: [
        "Targets/**",
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
